[tool.poetry]
name = "empire-bc-security-fork"
version = "4.8.4"
description = ""
authors = ["BC Security <info@bc-security.org>"]
readme = "README.md"
homepage = "https://github.com/BC-SECURITY/Empire"
repository = "https://github.com/BC-SECURITY/Empire.git"
packages = [
    { include = "empire.py" },
    { include = "empire/server/**/*.py" },
    { include = "empire/client/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
urllib3 = "*"
requests = "^2.24.0"
setuptools = "*"
pydispatcher = "*"
macholib = "*"
dropbox = "*"
pyOpenSSL = "*"
pyinstaller = "*"
zlib_wrapper = "*"
netifaces = "*"
jinja2 = "*"
xlutils = "*"
bcrypt = "*"
pyparsing = "*"
PyMySQL = "^0.10.1"
SQLAlchemy = "^1.3.20"
PyYAML = "^5.3.1"
SQLAlchemy-Utc = "^0.11.0"
prompt-toolkit = "^3.0.9"
terminaltables = "^3.1.0"
docopt = "^0.6.2"
humanize = "^3.2.0"
pydantic = "^1.8.1"
pycryptodome = "^3.10.1"
cryptography = "^37.0.3"
Flask-SocketIO = "^5.0.1"
python-socketio = "^5.2.1"
jq = "^1.1.3"
websockify = "^0.10.0"
pyperclip = "^1.8.2"
pyvnc = {git = "https://github.com/BC-SECURITY/pyVNC.git"}
# Donut breaks with Python 3.10 and hasn't been updated since 2019.
# See https://github.com/TheWover/donut/issues/107 for more detail
# The BC-SECURITY fork brings in the changes from S4ntiagoP's pull request
# https://github.com/TheWover/donut/pull/101
donut-shellcode = {git = "https://github.com/BC-SECURITY/donut.git"}
Flask = ">=2.1.2"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
isort = "^5.10.1"
black = "^22.1.0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
supported_extensions = ['pxd', 'py', 'pyi', 'pyx', 'plugin']

[tool.black]
extend-exclude = '''
    (empire/server/data*)
    | (empire/server/downloads*)
    | (empire/client/generated-stagers*)
    | (empire/client/downloads*)
'''
#include = '.*\.(plugin)$'
